### ISSUE TITLE
Downloads from 2017-05-01 are broken

### ISSUE THREAD

**Issue by Themanwithoutaplan** [HTTPArchive/httparchive#105]
The CSVs for 1st May are 0 bytes.

**Comment by rviscomi** [comment]
Confirmed. @pmeenan could this be a side effect of the new agents?

**Comment by pmeenan** [comment]
Anything is possible but it seems unlikely or we wouldn't have gotten actual crawl results.  Hore likely things that come to mind:

1 - The crawl completed on May 14 and a new one kicked off on May 15.  If the CSV generation lags the crawl completion by a day it may have grabbed the wrong crawl and tried to dump the new one.

2 - The CSV generation code choked on something with the database structure (maybe related to the table cleanup).  The actual database table dumps look to be in-line (size-wise) with previous crawls so it appears to be CSV-specific.

**Comment by rviscomi** [comment]
Thanks. I'll look into retrying CSV generation with an explicit date.

**Comment by pmeenan** [comment]
Just to set a timetable to validate, the next crawl is running quite a bit faster from a bunch of optimization and is probably 5 days or so from completing.  If there's a more fundamental problem than just picking the wrong table because of timing it would be good to figure it out before then.

**Comment by Themanwithoutaplan** [comment]
Any chance of running the dumps manually? Dumping to CSV is a bit of a PITA with MySQL because the paths are hardwired but it should still be possible. Happy to provide the command-line foo if that's any help.

**Comment by rviscomi** [comment]
Manually running bulktest/update.php with May 1 2017. When it gets to the CSV and MySQL dumps, here's the output:

```
6. Mysqldump & wrap up...
17:48:19 Dump pages table:
17:48:34 Dump pages table CSV:
mysqldump: Got error: 1290: The MySQL server is running with the --secure-file-priv option so it cannot execute this statement when executing 'SELECT INTO OUTFILE'
gzip: /tmp/May_1_2017.1495475299/pages.txt: No such file or directory
```

From https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_secure_file_priv:

> This variable is used to limit the effect of data import and export operations, such as those performed by the LOAD DATA and SELECT ... INTO OUTFILE statements and the LOAD_FILE() function. These operations are permitted only to users who have the FILE privilege.

The variable is currently set as follows:

```sh
mysql> SHOW VARIABLES LIKE "secure_file_priv";
+------------------+-----------------------+
| Variable_name    | Value                 |
+------------------+-----------------------+
| secure_file_priv | /var/lib/mysql-files/ |
+------------------+-----------------------+
```

Maybe the MySQL service was started using different configs before the May 1 crawl. I can look into unsetting this config so it doesn't affect future crawls.

**Comment by Themanwithoutaplan** [comment]
Right, the mysql user must have permission to right in the relevant folder. This is such a pain that it's possibly worth investigating alternatives.

**Comment by rviscomi** [comment]
> This is such a pain that it's possibly worth investigating alternatives.

Yeah. What do you have in mind?

**Comment by rviscomi** [comment]
One question I have is whether the tmpDir is even necessary. The sql dump pipes the mysqldump output to gzip, which writes to the downloads dir.

Compare L#226 with L#

**Comment by Themanwithoutaplan** [comment]
You can't do that with the CSVs because these are produced by the server itself, whereas the SQL is produced by the mysql client. Hence, the difference with regard to permissions.

**Comment by pmeenan** [comment]
I disabled the secure_file_priv setting (no idea how it got enabled but maybe a default changed with a MySQL update).  /tmp must have been something MySQL did internally as part of the dump because the actual export appears to write directly to the downloads directory.

The csv's are available for download now.

**Comment by Themanwithoutaplan** [comment]
This looks like a reasonable alternative http://www.mysqltutorial.org/mysql-export-table-to-csv/ Much more control over where the dump happens. But I suspect the server's user will still need permission to write in the folder.

**Comment by Themanwithoutaplan** [comment]
Thanks @pmeenan

**Comment by Themanwithoutaplan** [comment]
@pmeenan it looks like the runs on 2017-05-01 were generally a bit faster. Do we have any numbers for this? I saw you mention that there were changes due a change in the architecture. The agents have moved from Windows VMs to Linux ones, right?

**Comment by pmeenan** [comment]
Correct.  I'm much more comfortable with the performance numbers now as the servers are no longer heavily oversubscribed.  DNS in particular on the Windows VM's used to have some outliers that would skew the numbers.  I don't have aggregate numbers on the shift though.

The Linux VM's look to be performing much more consistently and the physical hosts have a few spare CPU cycles (hovers in the 80-95% utilization range).  We'll probably start exposing more performance numbers as part of the UI going forward.
