### ISSUE TITLE
Any upstream size data?

### ISSUE THREAD

**Issue by danlisarice** [HTTPArchive/httparchive#114]
Do you have transfer size for the upstream direction for all the requests?  I assume the transfer size charts are just the data going from the server to the browser?

**Comment by rviscomi** [comment]
Hi Dan. Yes the transfer size charts like this are referring to the average download size:

![image](https://user-images.githubusercontent.com/1120896/26983502-03c5decc-4d0a-11e7-9992-2342bea3b814.png)

If you wanted to find out the size of the requests themselves, you could query the [requests](https://bigquery.cloud.google.com/table/httparchive:runs.latest_requests) table like this:

```sql
SELECT AVG(reqHeadersSize) FROM [httparchive:runs.2017_05_15_requests] WHERE mimeType = 'application/javascript'
```

The result is 448.7 bytes.

**Comment by pmeenan** [comment]
Not sure if it is in the SQL tables but the HAR files have a bytesOut measurement (though it is usually a tiny rounding error in the grand scheme of things).

**Comment by andydavies** [comment]
Have seen clients where upstream is an issue - mainly due to the size of
cookies attached to each request

**Comment by rviscomi** [comment]
Yeah, here's a relevant thread from the forum: https://discuss.httparchive.org/t/size-of-document-cookies/49

**Comment by danlisarice** [comment]
Thanks I will do some queries and poke around in the data. Access networks can be pretty asymmetrical with different US and DS loss attributes and I am noodling on upstream packet sizes, counts and the impact on physical layer efficiencies for a variety of different traffic loads including web surfing.

**Comment by rviscomi** [comment]
Looks like this is resolved. Closing.
