### ISSUE TITLE
Thumbnails are broken

### ISSUE THREAD

**Issue by Themanwithoutaplan** [HTTPArchive/httparchive#118]
Don't know how long this has been the case but the URL for thumbnails is incorrect.

For example `http://httparchive.webpagetest.org/thumbnail.php?test=170601_1_5ST&width=200&file=video_1/frame_0000.jpg`
should be something like `http://httparchive.webpagetest.org/thumbnail.php?test=170601_1_5ST&width=200&file=video_1/ms_001928.jpg`

Looks like all thumbnails are being returned as `frame_0000.jpg` which suggests the lookup code is failing. For the beta you should be able to reuse the code from mamasnewbag that parses the XML to get the image path.

**Comment by rviscomi** [comment]
@pmeenan can you take a look?

**Comment by pmeenan** [comment]
The filmstrip's themselves are [ok](http://httparchive.webpagetest.org/video/compare.php?tests=170601_1_5ST-r:1-c:0), it is the HA UI side of things pointing to the wrong images.  This is probably because the agent switch also added support for 60fps video capture which results in different file names.  I think somewhere buried in the HA UI code it manualy assembles the frame file names instead of using the file names in the HAR (looking now to see if I can track down the code).

**Comment by Themanwithoutaplan** [comment]
FWIW the Python code I wrote for this includes tests. https://bitbucket.org/charlie_x/python-httparchive/src/118c381a1e58e40e3fc57fdf13fcf759cc212a80/httparchive/views/filmstrip.py?at=default&fileviewer=file-view-default

**Comment by pmeenan** [comment]
Code is [here](https://github.com/HTTPArchive/httparchive/blob/master/filmstrip.js).  It pulls the frame times from the HAR and constructs the file names itself directly.  The video frames in the XML response have the actual file names:

```
<videoFrames>
    <frame>
        <time>0</time>
        <image>
            http://httparchive.webpagetest.org/getfile.php?test=170601_1_5ST&video=video_1&file=ms_000000.jpg
        </image>
        <VisuallyComplete>0</VisuallyComplete>
    </frame>
    <frame>
        <time>1132</time>
        <image>
            http://httparchive.webpagetest.org/getfile.php?test=170601_1_5ST&video=video_1&file=ms_001132.jpg
        </image>
        <VisuallyComplete>0</VisuallyComplete>
    </frame>
...
```

It will still need to parse the file name out and construct the thumbnail URL from it.

**Comment by Themanwithoutaplan** [comment]
The relevant PHP code is in https://github.com/HTTPArchive/httparchive/blob/master/filmstrip.js#L31

**Comment by rviscomi** [comment]
Given that we're not planning to build standalone pages for each test result in v2, I'll mark this as wont-fix.
