### ISSUE TITLE
switch to Android phones

### ISSUE THREAD

**Issue by stevesouders** [HTTPArchive/httparchive#12]
the iOS test agent is far behind Android - we should switch

See this WPT bug: https://github.com/WPO-Foundation/webpagetest/issues/229

**Comment by RByers** [comment]
FWIW we've been using HTTP archive for compatible data for blink API decision making.  A big gap for us now is the lack of much data for mobile UAs.  Using Chrome in emulation mode would be perfect for our use case where performance doesn't matter.

**Comment by pmeenan** [comment]
Have you looked at the har data we are currently collecting as part of the "android" crawl?  That is Chrome in emulation mode and the configuration we will be scaling up for broader mobile testing.

Currently it's getting data for the top-5000 list (same as iPhone) but should include bodies and everything else that we collect from desktop crawls.  The hars should be available in Google Cloud Storage in the directories prefixed with "android" (the 3/1 and later crawls will have the best body data).

Timeline wise the plan is to switch the desktop default data to use the Chrome crawl from IE and continue IE testing to a hidden database for a few more crawls.  At the same time we will switch the mobile data to use the android crawl while still collection iPhone test data (and both will initially still be limited to 5k).  Once we are comfortable the change will stick and there is no use for collecting more IE data we will switch those VM's over to run the Chrome mobile emulation testing and ramp the mobile testing up to 500k pages.

**Comment by RByers** [comment]
> Have you looked at the har data we are currently collecting as part of the "android" crawl?

Yep, the data looks great except that it's not enough sites to really be that useful for most of my situations.  From this discussion I had assumed it was being collected on real devices and so unlikely to ever be more than a few thousand sites.  But instead it sounds like you're doing exactly what I had hoped - that's awesome, thanks!

**Comment by stevesouders** [comment]
Switching next month but it's been running for months successfully.
