### ISSUE TITLE
O(10000) firstHtml requests are certificate checks

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive#120]
```sql
SELECT
  COUNT(0) AS volume,
  resp_content_type
FROM
  [httparchive:runs.2017_06_15_requests]
WHERE
  firstHtml = TRUE
GROUP BY
  resp_content_type
ORDER BY
  volume DESC
```

volume | resp_content_type
-- | --
196243 | text/html; charset=UTF-8
118385 | text/html; charset=utf-8
96333 | text/html
16070 | text/html;charset=UTF-8
**13874** | **application/ocsp-response**
5170 | text/html;charset=utf-8
3823 | text/html; charset=windows-1251
3722 | text/html; charset=ISO-8859-1
2060 | text/html; charset=iso-8859-1
1357 | text/html; charset=gbk
1276 | text/html;charset=ISO-8859-1
1010 | text/html; charset="UTF-8"
640 | text/css
588 | text/html; charset=WINDOWS-1251
585 | text/html; Charset=utf-8
**580** | **application/x-x509-ca-cert**

@pmeenan is this WAI?

**Comment by pmeenan** [comment]
Can you pull out a few sample URLs that I can use for testing?  Should be easy enough to fix (not WAI but not unexpected).

**Comment by pmeenan** [comment]
Out of curiosity, do you know where firstHtml  is determined for the database?  Just in case HA has logic outside of WPT.

**Comment by rviscomi** [comment]
Ah looks like it's determined as the request with the first 200 response: https://github.com/HTTPArchive/httparchive/blob/814502e7ac84f61c46b96275bce1b4cf092150af/bulktest/batch_lib.inc#L664-L669

This URL appears 2800 times as firstHtml: `http://s2.symcb.com/MHEwbzBNMEswSTAJBgUrDgMCGgUABBS56bKHAoUD%2BOyl%2B0LhPg9JxyQm4gQUf9Nlp8Ld7LvwMAnzQzn6Aq8zMTMCEH7hSm9v7%2FLTfz%2BtZU062rSiHjAcMBoGCSsGAQUFBzABBAQNMAsGCSsGAQUFBzABAQ%3D%3D` and it's `application/ocsp-response`.

**Comment by andydavies** [comment]
Suspect original archive code predates widespread OCSP adoption

Won't apply to archive but in WPT multi step tests often see a beacon fired
during unload of previous plate turn up as first request

(I should probably raise a WPT issue for it)

**Comment by rviscomi** [comment]
I'll take this since it's a bug on the HA side. 96% of firstHtml responses contain `text/html` so I'll update the definition to be "the first 200 response having content type containing `text/html`".

**Comment by igrigorik** [comment]
As an aside, presumably these are sites with EV-certs being validated?
