### ISSUE TITLE
Chromium UseCounter data is missing?

### ISSUE THREAD

**Issue by mikewest** [HTTPArchive/httparchive#133]
I might have missed data moving around, but I can't seem to find UseCounter data in recent runs on BigQuery. That is, the following query returns data when executed against `2017_07_15_chrome_pages`:

```
SELECT 
  url,
  JSON_EXTRACT(payload, '$._blinkFeatureFirstUsed.Features.CrossOriginTextScript') AS feature
FROM [httparchive:har.2017_07_15_chrome_pages]
HAVING feature IS NOT NULL
LIMIT 500
```

But doesn't find anything when executed against `2017_08_01_chrome_pages`:

```
SELECT 
  url,
  JSON_EXTRACT(payload, '$._blinkFeatureFirstUsed.Features.CrossOriginTextScript') AS feature
FROM [httparchive:har.2017_08_01_chrome_pages]
HAVING feature IS NOT NULL
LIMIT 500
```

In fact, I don't see a `Features` property in the `payload` blob anymore; has the data moved elsewhere?

**Comment by pmeenan** [comment]
I'll take a look but it may be a few days to sort everything out.  Testing on the public wpt I can still get the features so they are still in the traces and able to be extracted.

I poked at a few archived tests on HA and the traces were empty so there's at least a couple of different issues going on that I need to look at (the features should be extracted on the agent so even the traces missing on the server wouldn't be an issue just by itself).

**Comment by rviscomi** [comment]
Pat, anything I can do to help debug?

**Comment by pmeenan** [comment]
If you can tell when they stopped showing up and if they are missing in all tests it may help narrow it down.  My current guess is something in the archiving of the results is removing them before the har's are generated but I'll have to watch the current crawl to get a better feel for what is happening.

At the same time it looks like Chrome 61 may have changed the device emulation stuff so I need to look into that to make sure the mobile crawl is working right (haven't verified but saw some tests on the public wpt linux agents with incorrect screenshots).  Exciting times!

**Comment by rviscomi** [comment]
It looks like the bug first started in the 8/1 crawl when the Chrome version went from 59 to 60. It's also definitely affecting all tests.

```sql
SELECT COUNT(0) FROM [httparchive:har.2017_08_01_chrome_pages] WHERE payload CONTAINS "_blinkFeatureFirstUsed"
```

0 results. (474975 for 07_15)


Let me know if there's anything else I can do to help

**Comment by pmeenan** [comment]
So far it looks like the feature usage files are on the server but they are basically empty so it is something on the agent side (or test options) and not related to the archiving.  I tweaked a few things just in case to make sure the feature usage is always recorded regardless of the test options and ran a couple of tests through the API manually and it appears to be working but I'm waiting for some new tests to get submitted to be sure.  The Sept 1 crawl has 1 more round of resubmits to go through but since it is resubmitting failed pages I may not know for sure until the Sept 15 crawl starts producing data.

It does look like the Sept 1 crawl is also missing the feature data so the earliest we can expect to see it back is the Sept 15 crawl.

Still not sure what caused it to break (or if I worked around whatever broke).

**Comment by rviscomi** [comment]
Thanks Pat. Did your tweaks also account for missing _TTIMeasurementEnd et al metrics?

**Comment by pmeenan** [comment]
It shouldn't but if something caused the traces to be missing entirely it is possible it did. The TTIMeasurementEnd metrics were present in the one-off test I ran.

**Comment by pmeenan** [comment]
Current guess is that Chrome 60 changed how it handles the trace categories string (or added a lot more trace events by default).  We were explicitly passing a trace categories param of the list of categories we wanted but no "-*," at the beginning.  It is possible that we were getting all of the categories and blowing through a buffer somewhere or it was just broken without the explicit filter.

One of the tweaks I made to the agent is to always include the feature usage category even if it wasn't requested and I turned off the explicit list of categories we were passing in through to the test.  I also just added a check to make sure the categories list starts with a -*, just to be sure.

Fingers crossed that was the issue.

**Comment by pmeenan** [comment]
Looking through the filesystem it looks like feature usage data is coming in for the tail of the crawl requests for today so I think we're good for the next pass.

**Comment by pmeenan** [comment]
Should have made it into the 15th.  There should actually be a few records from the tail of the Sept. 1st crawl after the changes landed.

**Comment by pmeenan** [comment]
Just verified using @rviscomi's query that there were 492 records in the Sept 1 crawl so fingers crossed it should be good for the complete Sept 15 run.

```
SELECT COUNT(0) FROM [httparchive:har.2017_09_01_chrome_pages] WHERE payload CONTAINS "_blinkFeatureFirstUsed"
```
