### ISSUE TITLE
_URL for test page is wrong in HAR file

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive#140]
See http://httparchive.webpagetest.org/result/171201_3Y_7QMR/1/details/#waterfall_view_step1

The [har file](http://httparchive.webpagetest.org/export.php?test=171201_3Y_7QMR&run=1&cached=0&bodies=1&pretty=1) contains a `pages[0]._URL` value of `"https://fonts.googleapis.com/css?family=Lato:300,300i,400,400i,700,700i,900,900i"`. The expected value is `"https://stackblitz.com/"`.

Downstream, this is causing issues in HAR queries where unexpected resources are being returned in place of the base page URL.

Originally discovered by @jeffposnick

**Comment by pmeenan** [comment]
Should be fixed now (will be picked up for part of the 1/1 crawl and the full 1/15 crawl).  The page-level URL is now forced to match the test URL.
