### ISSUE TITLE
Service workers missing from 12/15 response bodies

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive#141]
For example, [this test](http://httparchive.webpagetest.org/result/171215_2B_4MC5/1/details/#waterfall_view_step1) includes a request for sw.js. It's not in the 12/15 response bodies table, despite the same resource being available in the 12/1 table.

This was originally reported by @jeffposnick in a query similar to this:

```sql
SELECT
  DISTINCT url
FROM
  `httparchive.har.2017_12_01_chrome_requests_bodies`
WHERE
  body LIKE '%new self.Workbox%' OR
  body LIKE '%new Workbox%'
```

This yields 74 results, while a query over the 12_15 table only yields 1 result (the workbox website HTML).

@pmeenan did anything change on the WPT side? This seems like a regression of #113.

**Comment by pmeenan** [comment]
Looks like it's mostly from Chrome 63 and 2 separate issues. 

#1 - 63 started logging some phantom network requests which WPT filtered out but that also filtered out the SW requests (only from dev tools, the netlog had them as well so the requests were still logged but the request ID from devtools was lost and that is used to match the response body.  I fixed that which should help.

#2 - We aren't reliably seeing the request for the worker js in dev tools.  With the change to plznavigate in 63 it may have broken something there (re-opened the [devtools issue](https://github.com/ChromeDevTools/devtools-protocol/issues/36) and they are looking into it).

**Comment by mattto** [comment]
Just adding a "Me too!" comment... I work on Chrome's SW implementation and just now tried to use HTTPArchive to investigate how SWs are used in the wild. Would be good to have this working again. On the DevTools issue it looks like there was some clue about off-main-thread-networking?

**Comment by pmeenan** [comment]
I'm planning to add a safety net to re-fetch any missing bodies (using the same request headers). That should fill any missing bodies from dev tools.

________________________________

**Comment by pmeenan** [comment]
This should be fixed now.  WebPageTest will backfill any missing response bodies that it couldn't get from the browser by re-fetching them.  Not elegant but works.  I'll leave it open until we can verify with the Feb 1 crawl (it will be missing for the 1/2 day or so that has been running so far but that's less than 10% of the crawl)

**Comment by mattto** [comment]
Thank you!

**Comment by rviscomi** [comment]
```sql
SELECT
  DISTINCT url
FROM
  `httparchive.har.2018_02_01_chrome_requests_bodies`
WHERE
  body LIKE '%new self.Workbox%' OR
  body LIKE '%new Workbox%'
```

Testing against the Feb 1 crawl shows 103 results, so it seems like this has been fixed. Thanks @pmeenan!

@jeffposnick feel free to reopen if you're still seeing issues.

**Comment by jeffposnick** [comment]
Looks good! Thanks!
