### ISSUE TITLE
I'd love to be able to compare side by side stats for a website against average

### ISSUE THREAD

**Issue by nolanvinny** [HTTPArchive/httparchive#31]
The stats feature is great.   But I'd love to be able to compare an individual website to see how it stacks up against average statistics across the web.  For example, are my transfer sizes larger than average, etc.

**Comment by stevesouders** [comment]
You can view individual stats for a website. I don't think plotting that against the average across the entire web is very useful. If we could do it vs competitors or a specific vertical market perhaps. Closing.
