### ISSUE TITLE
Interesting Stats Sugestion: Average Bytes per Page by User Observed Category 

### ISSUE THREAD

**Issue by redradioflyer** [HTTPArchive/httparchive#34]
Hello,

My suggestion for the "Interesting Stats" page is a chart that tracks "Average Bytes per Page by User Observed Categories."

This chart would be visually and structurally similar to the pie chart named "Average Bytes per Page by Content Type," but the wedge categories would be tied to high level content categories that the average non-technical visitor would relate to. Example categories might include, Page Text Content (Articles, etc), Page Style & Structure (site logo, page layout, etc.), Advertising, Page Image Content (non-advertising or article specific images), etc.
Given the difficulty of reliably identifying advertising images vs content images this may only be reasonable to provide in the Top 100 URLs category (or it may be totally unreasonable to provide at all), but it would still be very interesting to see the results. 

In particular, the ratio of data downloaded by a page visitors that is valued or sought by the visitor (i.e. content, page style, etc) versus data downloaded to create value for the page operator (i.e. advertising, etc) may be of interest. This ratio may be increasingly important information as more and more US based ISPs move toward data cap and fee based models and advertisers move toward data heavy advertising like auto-playing audio and video.

**Comment by stevesouders** [comment]
The challenge is mapping resources to categories.
