### ISSUE TITLE
Contributing & Private Instances

### ISSUE THREAD

**Issue by ericduran** [HTTPArchive/httparchive#36]
Hi :)

I'm working on setting up a private instance and there are some pain-points which I know the project is aware off. I wanted to open an issue to start marking sure some of the improvements I want to make are ok or if not which route I should go.

Some Ideas:
 - Cleaning up the mysql calls, Right now the code base seems like it needs an older version of php to run (It's running fine on 5.5.16 locally but throwing a lot of future deprecated warnings)
 - Where should I contribute documentation? The wiki seems empty. I'm ok starting it or do we want to start with a Private-Instance.md file and document it there? (I know there various blog post on setting this up just seems like there should be something here)

Crazy Ideas:
 - Potentially migrating to some sort of micro-framework (I can do this on a separate repo if someone thinks is a good idea but personally I was thinking silex so keeping it php to potentially minimized the amount of work needed)

Thoughts? Also if there's already an effort to do any of what I mention I'm available to help.

In the mean time I'll continue on getting my instance up and running.

**Comment by mrfaizal** [comment]
Hey Eric, did you happen to document your experience getting a private instance running?

**Comment by andydavies** [comment]
@mrfaizal Barbara Bermes wrote about setting up a private instance here - http://www.bbinto.me/performance/setup-your-own-http-archive-to-track-and-query-your-site-trends/

**Comment by mrfaizal** [comment]
Thanks @andydavies.  That article is a couple years old -- I think some more recent commits might have broken things:

$ php bootstrap.inc
PHP Notice:  Undefined variable: gChromeDir in /var/www/httparchive/utils.inc on line 31
PHP Notice:  Undefined variable: gAndroidDir in /var/www/httparchive/utils.inc on line 32
PHP Parse error:  syntax error, unexpected '[' in /var/www/httparchive/crawls.inc on line 179

**Comment by ericduran** [comment]
@andydavies @stevesouders is it cool if I add a setup instruction to the wiki over at https://github.com/HTTPArchive/httparchive/wiki?

I'm doing a local set up now and want to track it all somewhere.

**Comment by stevesouders** [comment]
Hi, Eric. 

It would be GREAT to have more instructions on setting up private instances. Please go ahead and add a doc. 

Thanks, Steve
