### ISSUE TITLE
Stats for HTTP/2 vs HTTP 1.1 connections

### ISSUE THREAD

**Issue by datahog** [HTTPArchive/httparchive#37]
Many servers and browsers are just beginning to implement support for HTTP/2. Now is the perfect time to begin tracking when web servers begin supporting HTTP/2, to get a good and complete idea of how quickly it's adopted.

**Comment by stevesouders** [comment]
We're switching to Chrome soon. We should track this.

**Comment by igrigorik** [comment]
This is now live, you can see example query here: https://discuss.httparchive.org/t/http-2-adoption/792/7
