### ISSUE TITLE
Wrong response body in .har files

### ISSUE THREAD

**Issue by foolip** [HTTPArchive/httparchive#41]
In http://www.archive.org/download/har_httparchive_2014_11_15_B/bodies.zip there's a 141115_B_6QAZ.har.gz in which the response body seems to have been associated with the wrong URL.

The JavaScript resource starting with "!function(e,t){" and containing the string "caretRangeFromPoint" claims to come from https://fonts.googleapis.com/css?family=Montserrat:400,700 but that isn't the case. Load https://app.careerplug.com/user/sign_in and note that the same resource is actually from https://cpats.s3.amazonaws.com/assets/application-1efdbd9dfc7dc160c2d6d998ea3113b8.js

This seems like a bug.

**Comment by stevesouders** [comment]
Has this happened more recently?

**Comment by foolip** [comment]
I haven't used more recent data nearly as much, so if it's still a problem it's unlikely that I would have noticed it. A quick way to check might be to see if there's any entry where the URL contains "fonts.googleapis.com/css"  but the body contains "function(" or some other very JavaScript-y string.

**Comment by stevesouders** [comment]
Please re-open if this is still an issue.
