### ISSUE TITLE
Invalid JSON escapes in som .har files

### ISSUE THREAD

**Issue by foolip** [HTTPArchive/httparchive#43]
150101_S_FCFN.har.gz has one text/plain (actually binary) resource of size 72449 that contains the string `\v`, preceded and followed by non-ASCII stuff. One can pretend that it's latin-1 to decode it as a string and feed to a JSON decoder, but a conforming decoder will choke on the invalid escape. A literal backslash should be `\\`.

This is the full list of files with some similar problem in the 20150101 data set:
150101_M_CEM3.har.gz
150101_M_CP1B.har.gz
150101_M_CJH1.har.gz
150101_M_CNGD.har.gz
150101_M_CJAY.har.gz
150101_N_CXC4.har.gz
150101_N_D0X9.har.gz
150101_N_D92B.har.gz
150101_N_DDK3.har.gz
150101_N_D91W.har.gz
150101_N_D1E7.har.gz
150101_N_D265.har.gz
150101_P_DVYC.har.gz
150101_P_DE6N.har.gz
150101_P_DX2M.har.gz
150101_P_DT61.har.gz
150101_P_DH3X.har.gz
150101_P_DR1P.har.gz
150101_P_DNZS.har.gz
150101_P_DFQH.har.gz
150101_P_DJYP.har.gz
150101_P_DVCD.har.gz
150101_P_DQSA.har.gz
150101_P_DW0X.har.gz
150101_P_DH55.har.gz
150101_P_DFCY.har.gz
150101_Q_EAVE.har.gz
150101_Q_E6BK.har.gz
150101_Q_ED93.har.gz
150101_Q_EF7D.har.gz
150101_Q_EC2K.har.gz
150101_Q_E1FS.har.gz
150101_R_EYCP.har.gz
150101_R_EXFJ.har.gz
150101_R_ENYH.har.gz
150101_R_ES4B.har.gz
150101_R_F35E.har.gz
150101_R_EYX4.har.gz
150101_S_FAF0.har.gz
150101_S_F96V.har.gz
150101_S_FHTH.har.gz
150101_S_FCFN.har.gz

**Comment by stevesouders** [comment]
Sorry getting to this so late. If this is still an issue please re-open.
