### ISSUE TITLE
invalid location, status 400 returned from WPT when HA sends "IE8" for location parameter

### ISSUE THREAD

**Issue by mrfaizal** [HTTPArchive/httparchive#47]
My httparchive instance is sending the default "IE8" as the location parameter but my WPT private instance was returning status 400 and complaining that location parameter is invalid.  To unblock I've deleted the location parameter from the submitTest function so now WPT just uses its default, but I'm sure there is a proper fix.

**Comment by stevesouders** [comment]
For private instances, you need to customize the settings in bulktest/bootstrap.inc.
