### ISSUE TITLE
Missing “SpeedIndex” chart

### ISSUE THREAD

**Issue by marek-saji** [HTTPArchive/httparchive#48]
FAQ links (http://httparchive.org/about.php#SpeedIndex) to SpeedIndex chart on the main page (http://httparchive.org/trends.php#SpeedIndex), but the chart seems to be missing.

**Comment by stevesouders** [comment]
We no longer show the Page Load nor Speed Index charts since they emphasize absolute time values but our sample size is too small. I removed them from the FAQ.
