### ISSUE TITLE
First byte and start render time

### ISSUE THREAD

**Issue by bitinn** [HTTPArchive/httparchive#52]
I might be missing something here, does httparchive keep tracks of first byte and start render time nowadays? I found [it in the faq](http://httparchive.org/about.php#reqTotal) but not on any trend or stats or individual domain page (asides from the filmstrip and webpagetest result itself).

It would be very interesting to have this stat, at least across the top 1000 url, it gives developers a sense on how fast are the web is performing and a good goal to beat.

I also find #18 was working on such feature, was it added and later removed?

**Comment by pmeenan** [comment]
Yes but it's not reported in the UI because the test systems aren't really provisioned to do time-based measurements (they are oversubscribed so the times may not be entirely useful).  You can get at the underlying timings from the raw sql dumps or in bigquery.

**Comment by bitinn** [comment]
Thx, I should have guessed anything network dependent are difficult to measure. Would be great if http archive website provide a link to the bigquery page (as it's easier than processing locally)

For reference, here are some example:

http://bigqueri.es/t/what-are-the-render-start-times-by-quantiles/4
http://bigqueri.es/t/start-render-times-and-speed-index-for-yahoo-google-and-facebook/195

I will try to create a query for this purpose.
