### ISSUE TITLE
rgb image usage vs cmyk

### ISSUE THREAD

**Issue by chrisjohnson00** [HTTPArchive/httparchive#54]
would love to know the usage rate of cmyk images compared to rgb images. 
My company wants to do some custom work related to supporting scraping cmyk images from the web... i have a feeling it's not worth the time but haven't found data to support my feelings.

**Comment by stevesouders** [comment]
How would this be done?

**Comment by chrisjohnson00** [comment]
A quick search and I think it could possibly be detected by reading the PhotometricInterpretation value from the EXIF tags.  http://www.sno.phy.queensu.ca/~phil/exiftool/TagNames/EXIF.html shows the acceptable values as:
```
0 = WhiteIsZero 
1 = BlackIsZero 
2 = RGB 
3 = RGB Palette 
4 = Transparency Mask 
5 = CMYK 
6 = YCbCr 
8 = CIELab 
9 = ICCLab 
10 = ITULab 
32803 = Color Filter Array 
32844 = Pixar LogL 
32845 = Pixar LogLuv 
34892 = Linear Raw
```

**Comment by stevesouders** [comment]
We don't have access to the EXIF tags.
