### ISSUE TITLE
Show stats for most popular web font urls

### ISSUE THREAD

**Issue by ljm22** [HTTPArchive/httparchive#57]
Similar to use of Google libraries API stats. 

Show what proportion of pages were requesting the most popular google (or other) fonts for example... gives us a hint as to which fonts are likely to be already sitting in a new visitor's browser cache.

**Comment by stevesouders** [comment]
This is a bit too niche for the main UI. A possible way to start would be to do a bigqueri.es post and gauge interest in the results. Please re-open if it looks good.
