### ISSUE TITLE
Collect chromium UseCounter data

### ISSUE THREAD

**Issue by RByers** [HTTPArchive/httparchive#59]
For web compat work it would be extremely useful to be able to query which pages triggered specific [chromium use counters](https://www.chromestatus.com/metrics/feature/popularity).  @pmeenan, @igrigorik, @foolip and I talked about this briefly at the last BlinkOn and it sounded like it should be possible but I forget what the concrete plan was.

Use counters (both JS and CSS) are available today from chrome://histograms/WebCore.FeatureObserver, but perhaps that's not too convenient for the WPT pipeline?  Does WPT use the devtools protocol?  I could get the use counter data exposed via a more convenient channel if desired.

All we really need is the list of counters that were triggered by loading a given page (i.e. those which went up since the previous page load).  We don't need the absolute counts (I think a particular counter should go up by at most one per page load).  There may be some tricky issues with ensuring the data is up-to-date (may need to force an update by loading chrome://histograms a 2nd time) which I can help with.

If a list of dozens to hundreds of integers per page is a non-trivial amount of extra data to store, we could exclude reporting (or possibly even remove) counters which are triggered on a large fraction of pages.  Mostly what we care about are the rare features which we can see are being used somewhere but can't find a single concrete example for.

Any idea what the next steps here would be?

**Comment by pmeenan** [comment]
WPT has an extension that talks to the dev tools interface.  From what I understand from telemetry, there is the possibility to dump the histograms to a file with "--dump-browser-histograms".  Let me experiment a bit but we may be able to collect all of the histograms after the test completes and include them in the HAR.  Do you know if the use counters are included with the histogram dump?

I'm not concerned about the data size.  Compared to the video we keep it is trivial.  We're also talking about capturing traces with some set of categories and storing them as well for bulk analysis which would also dwarf the use counter sizes.

**Comment by RByers** [comment]
Despite it's name it looks like "--dump-browser-histograms" does include all the same information as chrome://histograms (from all processes, not just the browser process), so would work in general.

That can be quite a bit of data though (eg. mine is 1.2Mb uncompressed after a handful of page loads).  Would you really want to add 0.5TB to the total database size for this?  You could choose a subset of interesting histograms to trim this dramatically.  The JSON encoding is also pretty inefficient.

There's also an [outstanding issue](https://bugs.chromium.org/p/chromium/issues/detail?id=513059) with renderer histograms not getting flushed to the browser reliably.  I played with this a bit and I can see the FeatureObserver histogram update reliably only if I first navigate that renderer (eg. reload the page).  If it would help we could probably add some code to enable the WPT pipeline to flush the UseCounters for a specific renderer (or all renderers).  I assume WPT uses the normal Chrome navigation policy (throw away the renderer and create a new one for each new domain), right?

**Comment by pmeenan** [comment]
WPT Runs Chrome in process-per-tab mode so it will be a little different though not sure how much more reliable.  I can navigate to a blank page that I use for launch served by localhost if that is enough to trigger it.  I'd also be happy to pull it though any interface you'd like to expose.  Dev tools or a trace category (like blink.webplatform or something like that).  Bonus points, both of those are also available from WPT on actual devices (irrelevant for HA but more for FYI) while dumping the histograms isn't.

The data wont be in the database and 1.2MB uncompressed per test is a rounding error (we'd be gzipping it).  I'm mostly concerned about getting it reliably and consistently.

**Comment by igrigorik** [comment]
+1 for storing histograms, and I'd err on the side of "grab everything" instead of whitelisting. That way we will always have all the latest histograms and feature counters, as they become available, within the HAR dumps.

**Comment by RByers** [comment]
> WPT Runs Chrome in process-per-tab mode so it will be a little different though not sure how much more reliable. I can navigate to a blank page that I use for launch served by localhost if that is enough to trigger it. 

Thanks for the details, I'll spend some time playing with `--process-per-tab` to see how renderer histograms behave and let you know.

>  I'd also be happy to pull it though any interface you'd like to expose.

If we want all the histograms then using the command to dump to a file (or similar mechanism via the devtools protocol if that's better for you) is probably best.

> The data wont be in the database

Wait, I'm confused.  My goal is to be able to query the WebCore.FeatureObserver use counter for each page from BigQuery, which means it would have to get included in the HAR right?  I know size is an issue there if for no other reason than the costs of querying the ~1TB ($1-$5 per query) can be prohibitive for non-googlers using BigQuery.

**Comment by pmeenan** [comment]
Sorry, didn't mean to cause confusion.  The "database" on the http archive server just stores the page and request data. The HARs are assembled dynamically fom our side and dumped into cloud storage for bigquery.  They WOULD be available there, I just don't usually call that the database.

Ilya would know better but maybe there is a way to create separate tables/views/something from the HARs for things that get queried frequently to make them cheaper to parse.

**Comment by igrigorik** [comment]
> Ilya would know better but maybe there is a way to create separate tables/views/something from the HARs for things that get queried frequently to make them cheaper to parse.

We can definitely do that, once we determine what those tables are.

**Comment by RByers** [comment]
> Sorry, didn't mean to cause confusion. The "database" on the http archive server just stores the page and request data. The HARs are assembled dynamically fom our side and dumped into cloud storage for bigquery. They WOULD be available there, I just don't usually call that the database.

Ah, my bad - sorry!  I wasn't aware of that database.

**Comment by foolip** [comment]
Was this closed because it's fixed, or because it won't be fixed? Missing context :)

**Comment by stevesouders** [comment]
I didn't see a next step. Please reopen with a summary of what's to happen next.

**Comment by foolip** [comment]
@RByers, were you poking at the mechanism for extracting the histograms a while ago?

**Comment by pmeenan** [comment]
Re-opening.  I just landed code in Chrome that will log the use counters to tracing and make it trivial to extract.  I'll add the support to WPT to do it automatically and it will be included in the HAR's.  Going to be a bit before it hits the HA servers though because it will have to wait for Chrome 54 in 6-12 weeks.

**Comment by igrigorik** [comment]
\o/ ... awesome.

**Comment by foolip** [comment]
This is going to be amazing, 10<sup>10</sup> thanks @pmeenan!

**Comment by pmeenan** [comment]
Support just rolled out to WebPageTest for reporting the feature_usage data.  It is exposed in both the HAR files and the JSON API whenever a trace is collected with the "disabled-by-default-blink.feature_usage" category enabled (and if the installed browser supports it - just Canary right now.

there will be a blinkFeatureFirstUsed entry in the JSON (_blinkFeatureFirstUsed in the HAR) that contains a dictionary with dictionaries of the CSS and blink features that were reported as being used in the trace along with the time (in ms) that the feature was reported to be used (the time is relative to the start of the page load if timeline is captured, otherwise it is relative to the first reported feature being used).

The features will be mapped to their text names as much as possible (depending on how frequently I update the mappings).  Any unmapped features will be labeled as Feature_xxx or CSSFeature_xxx (where xxx is the feature number).

Once Chrome 54 rolls out to stable I will turn on trace collection for the feature usage in the HTTP Archive and update the issue.

Here is a [sample HAR](https://www.webpagetest.org/export.php?bodies=1&pretty=1&test=160815_1S_ba960bc4ac0d963a525be3d5ce300a08) and [JSON API](https://www.webpagetest.org/jsonResult.php?test=160815_1S_ba960bc4ac0d963a525be3d5ce300a08) result.

A trimmed version of the relevant HAR data looks like this:

```
"_blinkFeatureFirstUsed":{
  "CSSFeatures":{
    "CSSPropertyAliasWebkitAlignSelf":1635.795,
    "CSSPropertyAliasWebkitFlex":1635.32,
    "CSSPropertyTransformStyle":1630.458,
    "CSSPropertyFlexWrap":1635.713,
    "CSSPropertySize":3443.302,
    "CSSPropertyWebkitTapHighlightColor":1630.247,
    "CSSPropertyAliasWebkitColumnGap":3421.171,
    "CSSPropertyAliasWebkitAnimation":1635.142,
    "CSSPropertyMaxWidth":1628.892,
    "CSSPropertyTextDecoration":1627.653,
    "CSSPropertyBorderRight":1634,
    "CSSPropertyPosition":1628.465,
    "CSSPropertyColumnRule":3421.194,
    "CSSPropertyMaxHeight":1635.906,
    "CSSPropertyAliasWebkitAnimationDuration":1630.136,
    "CSSPropertySrc":1625.818,
    "CSSPropertyWillChange":20119.731,
    "CSSPropertyAliasWebkitBorderRadius":25022.448,
    "CSSPropertyAliasWebkitJustifyContent":1635.63,
    "CSSPropertyFlexShrink":3402.3,
    ...
    "CSSPropertyMarginLeft":1628.816
  },
  "Features":{
    "XMLHttpRequestAsynchronous":4112.871,
    "DocumentSetDomain":3460.889,
    "V8Performance_Navigation_AttributeGetter":21916.797,
    "CSSSelectorPseudoAny":20117.617,
    "HTMLMediaElement":3819.109,
    "BodyScrollsInAdditionToViewport":3728.459,
    "NavigatorVendor":25602.574,
    "XMLDocument":16413.551,
    "ReplaceDocumentViaJavaScriptURL":17681.315,
    "PrefixedDevicePixelRatioMediaFeature":12822.935,
    "CSSValueAppearanceNotNone":1628.569,
    "FormElement":3552.016,
    "V8SloppyMode":548.078,
    ...
    "StarInTimingAllowOrigin":2357.062
  }
}
```

**Comment by RByers** [comment]
Just looking at this after returning from vacation.  Looks awesome, thank you very much!  I'm really looking forward to playing with this in BigQuery when it's available!

**Comment by RByers** [comment]
Chrome 54 has been stable for awhile now.  @pmeenan can you please turn on the trace collection?

**Comment by pmeenan** [comment]
Hmm.  Trace collection has been enabled since October 1st but looking at cloud storage the HAR's all look like they are ~300 bytes (i.e. invalid).

We are also uploading the [raw traces](https://console.cloud.google.com/storage/browser/httparchive/traces-chrome-Nov_1_2016/?project=httparchive&pli=1) (with timeline and feature_usage enabled) but those are somewhat larger and less easy to query.

Looking into what is going on with the HAR's now

**Comment by pmeenan** [comment]
Think I tracked down the HAR issue but keeping an eye on it for a bit.  That means HARS with the feature usage won't be complete until the 12/1 run.

**Comment by RByers** [comment]
Great, thanks for digging into it!

**Comment by igrigorik** [comment]
> Hmm. Trace collection has been enabled since October 1st but looking at cloud storage the HAR's all look like they are ~300 bytes (i.e. invalid).

Wait, do you mean the current run will have empty HAR's?

**Comment by pmeenan** [comment]
Argh.  The traces were also not recording it because they were turning on "blink.feature_usage" instead of "disabled-by-default-blink.feature_usage".  That has also been fixed and I verified that the current stable is reporting it correctly so 12/1 should be good.

**Comment by pmeenan** [comment]
The current run will have a mix.  The tests that completed before I just fixed it will have empty HARs and the remaining will be fine.  The archiving code was running in parallel with the HAR code (by design) but was deleting the test data as it went (not by design),

If it's critical I can backfill the HARs by pulling the raw result archives down and running a batch script against them but that script doesn't exist yet and would probably take a few days to get sorted (not to mention the few hundred GB of test data I'd need to suck down).

**Comment by igrigorik** [comment]
I think we can live with it.. we'll just have to be careful with any analysis numbers for this run.

**Comment by pmeenan** [comment]
The normal results are fine and anything databased, it's just the uploaded HARs that have issues.  

Thinking about it, I can probably write something that will walk the cloud storage bucket and look for any invalid HARs and just fetch the HARs through the WPT front-end for each of them.  It will probably be painfully slow but it could repair individual HAR's (doesn't help with the bigquery pipeline though since that would have already run against the HARs).

**Comment by igrigorik** [comment]
Re-running the BQ pipeline is trivial. Getting a list of resources in the bucket should, in theory, also be fairly simple.. `gsutil ls -l gs://bucket` + filter by size?

**Comment by pmeenan** [comment]
Yep, it's just the process of fetching the HARs individually and uploading them that will take a lot of wall-clock time (few seconds per HAR) though it can easily be made parallel.

If I get a chance on Monday I'll take a look at implementing it and see how it goes.

**Comment by pmeenan** [comment]
Not as painful as I thought.  It is backfilling the ~45k tests that had truncated HARs right now and it should be done well before the crawl finishes.

**Comment by igrigorik** [comment]
@pmeenan you, sir, are awesome. 👍

**Comment by pmeenan** [comment]
I just verified that the 12/1 crawl is correctly collecting use counter data and reporting it in the HAR's.  [Here is an example](http://httparchive.webpagetest.org/export.php?test=161202_0_3&run=median&cached=0&bodies=1&pretty=1).

**Comment by RByers** [comment]
Awesome, thank you!  And it'll be exposed automatically in the BigQuery har tables, right?  I don't see it in BigQuery for 11/15 (but presumably that's due to the above issue?).

**Comment by igrigorik** [comment]
@RByers correct, the data will be available in BQ once this run is complete..

**Comment by ebidel** [comment]
Just a quick sanity check... on webpagetest.org I still need to use `disabled-by-default-blink.feature_usage` for the histogram data to show up in the .har. Should it be on by default?

**Comment by igrigorik** [comment]
+1 to enabling it by default.. That said, I'll defer to Pat on overhead costs, etc.

**Comment by pmeenan** [comment]
Correct.  I can make it part of the default options that get turned on with "timeline" but timeline can have some overhead associated with it (though the JS timing is invaluable so having it be opt-out for Chrome testing may make sense).

By default tracing isn't enabled at all and I'm not sure it makes sense to enable it by default just for the feature usage.

**Comment by RByers** [comment]
I think most users of tracing would not find it useful, so it's hard to argue that it's beneficial generally to be on by default I think.  But even the concept of "default trace categories" is a little unclear to me now that the trace UI requires you to select a profile ("web developer", etc.).  All that said, the volume should be no more than ~2000 entries per page load, so the overhead shouldn't be huge.  But I think tracing has suffered by a death-from-a-million problem, so trace folks would probably push back on making it on by default.

**Comment by pmeenan** [comment]
Sorry, I was talkign about "on by default for WPT tests", not tracing in general.  Still, the same largely applies that not a lot of developers are going to be using the feature usage data.

**Comment by ebidel** [comment]
Also, I'm trying to figure out how the CSS features captured map to the ids we expose on chromestatus. For example, "CSSFeature_616":

<img width="325" alt="screen shot 2016-12-06 at 10 07 53 am" src="https://cloud.githubusercontent.com/assets/238208/20937901/b4b85ad8-bb9d-11e6-8981-7b285f790261.png">

616 and 1114 aren't ids we get from UMA:
https://www.chromestatus.com/metrics/css/timeline/popularity/616
https://www.chromestatus.com/metrics/css/timeline/popularity/1114

**Comment by pmeenan** [comment]
I used to map the [CSS properties](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/frame/UseCounter.cpp?q=cssfeature&sq=package:chromium&l=1231&dr=C) to names but it looks like they change so I just pass the property number directly through as it was captured in the trace.  My guess is that it is going to have to depend on the build.

Looking at the code it looks like [histograms have their own remapping](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/frame/UseCounter.cpp?sq=package:chromium&dr=C&rcl=1481026846&l=54) of the ID's which is probably why it doesn't show in UMA as the same.

My guess is that those are actually the stable numbers and we should change the trace point to emit the mapped feature number instead of the property ID.

**Comment by pmeenan** [comment]
Re-opening for now to keep track of the change to use stable ID's for the CSS properties.  Pulling the chromium code now for a CL to fix it there.

**Comment by ebidel** [comment]
I can confirm that https://chromium.googlesource.com/chromium/src/+/master/third_party/WebKit/Source/core/frame/UseCounter.cpp is are the stable ids for css properties. We pull from that file for chromestatus.com metrics.

**Comment by pmeenan** [comment]
CR bug [created](https://bugs.chromium.org/p/chromium/issues/detail?id=671731).  Should be a 2-line CL and hopefully will be able to get it merged to Beta/Dev so it can land in 56.  Should have the CL ready in a few hours.

**Comment by pmeenan** [comment]
CL created and out for review: https://codereview.chromium.org/2558583002

**Comment by RByers** [comment]
Sorry about this guys, I should have noticed that we were using the unstable property IDs instead of the stable histogram bucket numbers in the trace.

**Comment by RByers** [comment]
Hey guys, I'm still not seeing any feature data in BigQuery.  It should be in the payload for the `pages` table, right?  Eg. this query returns no results:
```
SELECT url, payload
FROM [httparchive:har.2017_01_01_chrome_pages]
WHERE payload CONTAINS '_blinkFeatureFirstUsed'
```

**Comment by pmeenan** [comment]
Argh - I swear this feature is cursed.  There was a [spurious comma](https://github.com/WPO-Foundation/webpagetest/commit/25b102cd486faeaa06d6f40d05d0c11cdf50f5f2) being added to the file names (added when I was adding Time to Interactive support).

Nothing I can do for the 1/1 crawl but we caught the 1/15 crawl before HARs started being uploaded and I manually fixed the already-crawled bad filenames.

**Comment by RByers** [comment]
Thanks :-).  We'll get it working smoothly eventually I'm sure.  At least now we're mostly iterating on stuff with a 15-day cycle time instead of 6 weeks (chromium->stable) <grin>.

**Comment by RByers** [comment]
I've verified this is working in BigQuery now - eg. a query like:
```
SELECT 
  url,
  JSON_EXTRACT(payload, '$._blinkFeatureFirstUsed.Features.TimeElement') AS featureTime
FROM [httparchive:har.2017_01_15_chrome_pages]
HAVING featureTime IS NOT NULL
LIMIT 500
```
Will return the URLs of the pages which trigger the `TimeElement` counter (and the time at which it was triggered).

**Comment by pmeenan** [comment]
Woo Hoo.  Still waiting for the fixed CSS features to work their way through the Chrome release and then I'll close the issue (assuming I can avoid breaking something else).

**Comment by igrigorik** [comment]
@RByers where do we define TimeElement? I don't see it in https://chromium.googlesource.com/chromium/src/+/master/third_party/WebKit/Source/core/frame/UseCounter.h - is there another place I should be looking in?

**Comment by igrigorik** [comment]
For reference, the feature name definitions are spread across: 
- https://chromium.googlesource.com/chromium/src/+/master/third_party/WebKit/Source/core/frame/UseCounter.h#72
- https://chromium.googlesource.com/chromium/src/+/master/third_party/WebKit/Source/core/frame/UseCounter.cpp#57

Find the feature you're interested in and use `$._blinkFeatureFirstUsed.Features.<featurename>` as the JSON_PATH selector in the query -- see Ricks example above.

**Comment by RByers** [comment]
Only the `Feature` values in UseCounter.h can be used as above.  Soon (after M57) CSS properties will also work, but I believe you'll need to use `$._blinkFeatureFirstUsed.CSSFeatures.<css-property-id>` for those.

**Comment by igrigorik** [comment]
Thanks Rick, updated!

**Comment by ebidel** [comment]
https://www.chromestatus.com/metrics/feature/popularity and https://www.chromestatus.com/metrics/css/popularity also list the values for `<featurename>`!

**Comment by pmeenan** [comment]
As far as the time element goes, that is just calculated from the trace event since we emit the trace event on the first use and all trace events are timestamped.  The reported time is relative to the start of navigation.

If it helps, the WPT code that extracts the features (and everything else trace related) is [here](https://github.com/WPO-Foundation/trace-parser/blob/master/trace-parser.py#L434) (and yes, the ID # to name mapping is a static list that I update periodically).

**Comment by suzyh** [comment]
@pmeenan I'm looking at adding a new UseCounter histogram for animated CSS properties: https://codereview.chromium.org/2678143003. Rick suggested pinging you to ask about getting this histogram included in the HTTP Archive data when that patch is in. Are there instructions I can follow to do this, or is this something you'd have to do?

**Comment by pmeenan** [comment]
Looks like you are already generating a trace event with the right category and the name 'AnimatedCSSFirstUsed'.  Is there a lookup table somewhere that maps ID's for the features to strings?

I mostly just need to update the trace parser in WebPageTest to look for the new trace event name and map the strings and it should pass right through (once it makes it through to stable).

https://github.com/WPO-Foundation/trace-parser/blob/master/trace-parser.py#L434

**Comment by suzyh** [comment]
@pmeenan The histogram uses the same set of properties as the existing CSS properties histogram ('CSSFirstUsed') so I'd think you should be able to reuse that.

**Comment by suzyh** [comment]
@pmeenan FYI the UseCounter histogram for animated CSS properties has landed.

**Comment by pmeenan** [comment]
The code is now collecting the feature information though it will not show any until the change rolls out (to stable for the HTTP Archive, to Canary for WebPageTest with Canary).  Do you have a sample site that you know triggers the use counter so I can verify it is working as expected?

**Comment by rviscomi** [comment]
_blinkFeatureFirstUsed is being collected. Example analysis: https://twitter.com/rick_viscomi/status/857307225064394752

OK to close this?

**Comment by RByers** [comment]
Yes, I've been using this as well - thank you!

**Comment by igrigorik** [comment]
Anything extra we need to do for the CSS properties? Will that "just" show up in the subsequent runs?

**Comment by pmeenan** [comment]
They should just show up as an additional section in the blink features tree.  The trace parser already knows how to extract them.

**Comment by igrigorik** [comment]
Great. Do we have an ETA for when that should go live?

**Comment by pmeenan** [comment]
The regular CSS features should already be there.  The Animated ones will be there when the change rolls to stable (my guess is it made it into 59 so maybe another 6 weeks?)
