### ISSUE TITLE
Add connection_id to request table in MySQL dumps

### ISSUE THREAD

**Issue by robgjansen** [HTTPArchive/httparchive#61]
This is a proposal to add a connection_id to the requests table in the MySQL dumps, and start populating that field by tracking which socket was used for each request. The connection_id field only needs to be unique per page.

This would be helpful in understanding the full distribution of requests per TCP connection; as I understand it, currently only the average is available from the MySQL dumps as `pages.reqTotal/pages._connections`.

The socket is currently available in the HAR data. See more here:
https://discuss.httparchive.org/t/proposal-add-a-connection-id-to-requests/706

**Comment by igrigorik** [comment]
Rob, naive question: why? If we already have it in the HAR's, why is that not sufficient?

**Comment by robgjansen** [comment]
Where on earth are the HAR's? They are not listed on the HTTP Archive download page and I can't seem to find them after a quick search.

I was assuming the mysql dumps were consolidated versions of the HAR dumps that make it easier to query the data locally (I don't have Internet access where I am running my analysis). I thought the mysql dumps were the standard distribution method since its the only thing listed on the downloads page. What am I missing?

**Comment by igrigorik** [comment]
Rob, take a look at these pages:
- https://discuss.httparchive.org/t/quickstart-guide-to-exploring-the-http-archive/682
- https://discuss.httparchive.org/t/how-to-download-the-http-archive-data/679

**Comment by robgjansen** [comment]
Thanks for the links! I take it that my request to include an additional useful piece of information in the summary tables was denied, and so I'll have to download and process over 1 TB instead of 5 GB if I want it. Cheers!
