### ISSUE TITLE
HTTPArchive Private Instance not running tests

### ISSUE THREAD

**Issue by arunvsarma** [HTTPArchive/httparchive#64]
Hi, 
I have pulled the latest code and setup httparchive on my VM. I have also configured it with my private WPT instance. I used the addwebsite.php to add a website. This strangely didn't trigger the WPT test. The status table remained empty probably empty because the test did not run. Any ideas or reasons?
Regards,
Arun

**Comment by stevesouders** [comment]
Did you run batch_start.php? Have you read any of the articles about setting up a private instance of HA? The documentation and setup for a private instance is pretty slim - you're going to have to work with it a bit and read what's out there to get it going.

This isn't a discussion for github issues. Please use the HA discussion forum: https://groups.google.com/forum/#!forum/httparchive
