### ISSUE TITLE
Should service worker scripts be captured somehow?

### ISSUE THREAD

**Issue by RByers** [HTTPArchive/httparchive#66]
I'd like to analyze some data for scripts loaded into a ServiceWorker, but I'm not seeing the service worker resources in the httparchive data.  Eg:
```
SELECT page, url FROM [httparchive:har.android_feb_15_2016_requests]
WHERE page CONTAINS 'flipkart.com'
LIMIT 5000
```
does not return an entry for their `sw.js` file.

Is this something that could reasonably be added somehow?

**Comment by stevesouders** [comment]
We only track network requests. For example, we don't show requests that are read from the cache.

**Comment by RByers** [comment]
Sure, but don't you start with an empty cache, so that sw.js would be loaded from the network the first time?

**Comment by stevesouders** [comment]
Even if I do this in incognito, I don't see sw.js in Chrome Dev Tools. Can you produce a HAR file in Chrome Dev Tools that contains sw.js? If not, it seems like this is not being requested, or Chrome doesn't show it.

Pat would have to answer the API question.

**Comment by RByers** [comment]
Yes, I do, here's the [har I get](https://gist.github.com/RByers/2b63f0e6e438eb393dc612da9cb08fb8) - note `sw.js`.  Note that Flipkart only serves a service worker to mobile, so you need to use device mode to send a mobile UA string.  You can use the "sources" tab in dev tools to see if a service worker is being used for a given page.

**Comment by stevesouders** [comment]
sw.js shows up in Http Archive for Android:

http://android.httparchive.org/viewsite.php?pageid=149469#waterfall

**Comment by RByers** [comment]
Oh interesting, but not for the data [from Feb 15](http://android.httparchive.org/viewsite.php?u=http%3A%2F%2Fwww.flipkart.com%2F&l=Feb%2015%202016), which is the latest Android data I see in BigQuery.  @igrigorik is there fresher data here that's not yet available in BigQuery for some reason?

**Comment by igrigorik** [comment]
@RByers there was a regression in latest DataFlow SDK so I paused the automated imports... I can work around it though if its high priority.

**Comment by RByers** [comment]
Thanks @igrigorik - moved that to a separate issue.

@pmeenan are you aware of any reason why capturing the service worker resources may be unreliable / racy?  flipkart.com has depended on a service worker since at least November I believe, so it's odd that the data is in some runs and not others.  I assume you're careful to clear all the caches between runs, right?  Does whatever process you use for clearing the cache also delete any cached service workers?

**Comment by pmeenan** [comment]
The entire browser profile is destroyed between runs so the service worker will only get downloaded whenever it happens to get normally scheduled to download.  

Looking at a test run on the public WebPageTest it looks like the sw.js is downloading correctly: http://www.webpagetest.org/result/160428_39_bdfa188b910fee0d594f1a8ab4b57b79/1/details/

And the most recent run on the HTTP Archive seems to have loaded it: http://httparchive.webpagetest.org/video/compare.php?tests=160415_S_FEPZ-r:1-c:0

It's possible that the emulation in February was using a UA string that was from a version of Chrome that pre-dataed SW support and I believe Flipkart uses UA sniffing.

**Comment by RByers** [comment]
Thanks!

> It's possible that the emulation in February was using a UA string that was from a version of Chrome that pre-dataed SW support and I believe Flipkart uses UA sniffing.

Ah, ok - I could see it being something like that.  OK let's not worry about this further (thanks for all the help)!
