### ISSUE TITLE
Dates show in xaxis of charts are wrong

### ISSUE THREAD

**Issue by jawadhoot** [HTTPArchive/httparchive#69]
http://httparchive.org/viewsite.php?pageid=64226812

date shown is x axis are repeating year as "/15"  instead of "/16";
![untitled](https://cloud.githubusercontent.com/assets/19701781/15734354/63c30652-28ac-11e6-8428-77aaf4d67021.png)

**Comment by stevesouders** [comment]
Those dates are MM/DD - eg, June 15, July 15.
