### ISSUE TITLE
Need delete porn content

### ISSUE THREAD

**Issue by trustjohn** [HTTPArchive/httparchive#71]
We found a few sites that also have to be removed from your database (adult materials):

http://httparchive.org/viewsite.php?pageid=4438119
http://httparchive.org/viewsite.php?pageid=15062825
http://httparchive.org/viewsite.php?pageid=15007643
http://httparchive.org/viewsite.php?pageid=7004854
http://httparchive.org/viewsite.php?pageid=66769548
http://httparchive.org/viewsite.php?pageid=34552743
http://httparchive.org/viewsite.php?pageid=32177293
http://httparchive.org/viewsite.php?pageid=66464202

Thanks!

**Comment by stevesouders** [comment]
These sites have been flagged as adult content so we no longer show their filmstrips in HTTP Archive.

**Comment by trustjohn** [comment]
Display an insufficient measure flag. From the pages you can make the transition to some of the materials sites. For example the table of requests - where the reference to the prohibited materials, as well as on the Filmstrip, Video - which also can be seen prohibited content.It is necessary to exclude domains of Databases!!!Requests were sent to the domain registrant (AHNames), archive.org, icann.orgarchive.org - are already excluded from the Databases; Domains list: sadomax.com bizarre-tube.com myfuck.tv bondagezilla.com my18teens.com myteenvideo.com pornmage.com xxxshemaleporn.comThank you for your cooperation
At 6 Aug 2016 16:15:20 +0000 (+00:00) from Steve Souders <notifications@github.com>:
These sites have been flagged as adult content so we no longer show their filmstrips in HTTP Archive.
