### ISSUE TITLE
It is necessary to exclude domains of Databases!!!

### ISSUE THREAD

**Issue by trustjohn** [HTTPArchive/httparchive#72]
Display an insufficient measure flag. From the pages you can make the transition to some of the materials sites. For example the table of requests - where the reference to the prohibited materials, as well as on the Filmstrip, Video - which also can be seen prohibited content.

 It is necessary to exclude domains of Databases!!! 

Thank you for your cooperation

**Comment by igrigorik** [comment]
> It is necessary to exclude domains of Databases!!!

Why? HTTP Archive allows adult content, as it reflects web as it actually is.

**Comment by trustjohn** [comment]
ICAAN the filing, investigation was made in respect of a group of sites, and the criminal case by the court were blocked domains of the registrant, as well as from the hosting provider. All materials were removed from all the servers.

The court requests to all public records including your domain to excluded them from the database have been sent. 

My task is to control the exclusion of these domains of all public archives (analog webarchive.org),
as well as on all sites where there is mention of them.

We ask you to help us in solving our problems and eliminate these domains from your database, like other public sites.

Also, if necessary, we can send you a formal request for the exclusion of these domains.

Thanks!
It is very important that you send us to a meeting

**Comment by igrigorik** [comment]
I see, thank you for bringing this to our attention. Do you have any public links to the ruling / court request?

**Comment by trustjohn** [comment]
Unfortunately in our courts is prohibited to publish materials of the case on the Internet. We can only send a formal request to exclude domains from the database, such requests we sent to webarchive.org

in confirmation of my words, you can check yourself that these domains are excluded from the data base webarchive.org

**Comment by igrigorik** [comment]
This may be due to my own naivete, but exclusion on other sites does not seem sufficient -- in effect anyone could send such request without any proof. I'm not trying to obstruct, but personally I would like to see something more then a verbal claim.

**Comment by trustjohn** [comment]
Please tell us your email, will send you the necessary documents.

You have to consider that some documents are confidential and can not be uploaded to public access.

p.s. why the home page httparchive no email to which you can send documents?

**Comment by igrigorik** [comment]
Please use the email in my Github profile: https://github.com/igrigorik

**Comment by trustjohn** [comment]
You received our letter with the documents?

**Comment by igrigorik** [comment]
Updates via https://github.com/HTTPArchive/httparchive/commit/12a709da6080322a3fa97ebc5bda7af9b18580c4: 

- Filmstrip and WPT links are hidden for sites with adult content
- Resources in the request table are not linked for sites with adult content
