### ISSUE TITLE
Find a replacement for Alexa ranking

### ISSUE THREAD

**Issue by RByers** [HTTPArchive/httparchive#75]
@foolip added wrote [an example](https://docs.google.com/document/d/1cpjWFoXBiuFYI4zb9I7wHs7uYZ0ntbOgLwH-mgqXdEM/edit#) for how to sort an HTTP Archive BigQuery result with use counters by page rank:

```
SELECT 
  IFNULL(runs.rank, 1000000) AS rank,
  har.url AS url,
  JSON_EXTRACT(payload, '$._blinkFeatureFirstUsed.Features.HTMLMarqueeElement') AS feature
FROM [httparchive:har.2017_01_15_chrome_pages] AS har
LEFT JOIN [httparchive:runs.2017_01_05_pages] AS runs
ON har.url = runs.url
HAVING feature IS NOT NULL
ORDER BY rank;
```

Joining across the `har` and `runs` databases shouldn't really be necessary, should it?  Could we just get the `rank` included in the `har` `pages` table?

I thought I remembered some discussion on this in the past, but I can't find it - sorry if I just missed it.

**Comment by igrigorik** [comment]
It would require some plumbing, as the actual rank data is not available in HAR files. However, the larger problem here is that it's not clear if "rank" is something we can support in medium-longer term due to Alexa deprecation: https://github.com/HTTPArchive/hosts/issues/1

... ¯\_(ツ)_/¯

**Comment by RByers** [comment]
Whoa.  Yah rank is minor compared to that!

**Comment by igrigorik** [comment]
If you know of other sources we could bootstrap the host list (and ~rank), please chime in on the other thread! Definitely something we'll need to figure out sooner rather than later.

**Comment by foolip** [comment]
Is Alexa top million going to go away? @pmeenan said they'd reverted the decision.

**Comment by igrigorik** [comment]
AFAIK, it was "restored" but its future is uncertain: https://twitter.com/Alexa_Support/status/801167423726489600

**Comment by rviscomi** [comment]
Dropping off some notes:

- Cisco: https://umbrella.cisco.com/blog/blog/2016/12/14/cisco-umbrella-1-million/ contains lots of third party domains (eg fbcdn.net) and YouTube video servers (eg r5---sn-nx57ynls.googlevideo.com)
- Majestic: https://blog.majestic.com/development/alexa-top-1-million-sites-retired-heres-majestic-million/ contains URL shorteners (eg t.co) and censors porn category

**Comment by igrigorik** [comment]
Majestic ranking is.. [interesting](https://blog.majestic.com/development/majestic-million-csv-daily/):  

> when looking at which sites may be creating the most “waves” or “influence” in the world, raw link counts are not ideal, because sitewides can distort rankings. Similarly, we found some servers may have thousands of sites/domains linking to a site that are controlled by the same person or group, so some false positives there as well. By ranking based on IP Ranges, rather than others, the list looks more robust.

TBH, not sure if / how much we can trust this as a signal.  Cisco dataset seems more promising..

Also, we should probably consolidate this thread + https://github.com/HTTPArchive/hosts/issues/1.

**Comment by obto** [comment]
Updated link for Cisco's 1 million: https://umbrella.cisco.com/blog/cisco-umbrella-1-million
