### ISSUE TITLE
Bad data in Feb 1st

### ISSUE THREAD

**Issue by Themanwithoutaplan** [HTTPArchive/httparchive#76]
It looks like a couple of sites have `NULL` for the `numDomains` in the data for desktops from 2017-02-01:

http://www.expedia.it/
http://www.vosizneias.com/

**Comment by igrigorik** [comment]
This is due to https://github.com/HTTPArchive/httparchive/issues/74#issuecomment-277292367 -- let's continue there. We fixed the problem part-way through the Feb 1st crawl, which is why a subset of the records are affected.

**Comment by 99Edorde** [comment]
> It looks like a couple of sites have `NULL` for the `numDomains` in the data for desktops from 2017-02-01:
> 
> http://www.expedia.it/ http://www.vosizneias.com/

Me

**Comment by 99Edorde** [comment]
PHP
