### ISSUE TITLE
Stats About Performance of Categories of Websites from Alexa

### ISSUE THREAD

**Issue by ASalkever** [HTTPArchive/httparchive#9]
Ideally, would be nice to see performance stats in aggregate for, say, "travel", "shopping" "finance" etc - category based.

**Comment by igrigorik** [comment]
Added DMOZ join in https://github.com/HTTPArchive/bigquery/commit/250cb5cb69d716cb5e88f91dc16eb52945214659. Example for latest run: https://bigquery.cloud.google.com/table/httparchive:urls.20160915
