### ISSUE TITLE
Dump requests tables after current crawl completes

### ISSUE THREAD

**Issue by pmeenan** [HTTPArchive/httparchive#96]
[Disk space spiked up to 80%](http://httparchive.org/newrelic-dash/) and goes up ~10% per crawl because of the requests table growth.  We need to run the cleanup script between the end of this crawl and the beginning of the next.

**Comment by igrigorik** [comment]
Any reason why we can't or shouldn't automate it for the future?

**Comment by pmeenan** [comment]
Nope, I think Steve was just hesitant to do it previously in case something needed to be recalculated.

**Comment by pmeenan** [comment]
The 4/15 crawl looks like it is done.  Now would be a good time to make the first pass so we can make sure it gets all of the tables.

**Comment by rviscomi** [comment]
Should we wait until the done flag is set?

```
$ gsutil stat gs://httparchive/chrome-Apr_15_2017/done
No URLs matched: gs://httparchive/chrome-Apr_15_2017/done
```

**Comment by pmeenan** [comment]
No need as long as the database thinks the crawl is complete (which I'm pretty sure it does since it is exposed in the trends interface for both).

The HAR done flag is set by my archiving scripts which don't depend on the database and tend to lag the main crawl by a day or two.

**Comment by pmeenan** [comment]
Has this been done yet? The storage is still [hovering around 75%](http://httparchive.org/newrelic-dash/) and 1.7TB of the 2TB in use is in the mysql databases (1.6TB in just a few requests tables files)

240G    requestsdev.MYD
50G     requestsdev.MYI
56G     requestsdevSAVE.MYD - what is this?
7.7G    requestsdevSAVE.MYI - what is this?
74G     requestsie.MYD
11G     requestsie.MYI
295G    requests.MYD
57G     requests.MYI
4.2G    requestsmobiledev.MYD
861M    requestsmobiledev.MYI
698G    requestsmobile.MYD
146G    requestsmobile.MYI

Longer-term since the requests table is just used during the crawl we should decide if it needs to be moved from "dev" to prod (AFAIK, "dev" is where the crawl work is done) and maybe the prod copies can be dropped entirely.

Also, from the size of the requestsmobile tables files, I don't think the cleanup script has been cleaning them up on previous runs so it probably needs to be modified to get all the tables.

**Comment by igrigorik** [comment]
Not sure where the `SAVE` tables came from -- should be save to nuke. Ditto for `ie`. That said I'll defer to @rviscomi..

**Comment by rviscomi** [comment]
Before cleanup:

```
$ du -h /var/lib/mysql/httparchive/requests* | sort -hr
698G	/var/lib/mysql/httparchive/requestsmobile.MYD
295G	/var/lib/mysql/httparchive/requests.MYD
240G	/var/lib/mysql/httparchive/requestsdev.MYD
146G	/var/lib/mysql/httparchive/requestsmobile.MYI
74G	/var/lib/mysql/httparchive/requestsie.MYD
57G	/var/lib/mysql/httparchive/requests.MYI
56G	/var/lib/mysql/httparchive/requestsdevSAVE.MYD
50G	/var/lib/mysql/httparchive/requestsdev.MYI
11G	/var/lib/mysql/httparchive/requestsie.MYI
11G	/var/lib/mysql/httparchive/requestsandroid.MYD
7.7G	/var/lib/mysql/httparchive/requestsdevSAVE.MYI
4.2G	/var/lib/mysql/httparchive/requestsmobiledev.MYD
2.5G	/var/lib/mysql/httparchive/requestsandroid.MYI
861M	/var/lib/mysql/httparchive/requestsmobiledev.MYI
829M	/var/lib/mysql/httparchive/requestsiphone.MYD
176M	/var/lib/mysql/httparchive/requestsiphone.MYI
20K	/var/lib/mysql/httparchive/requestsmobile.frm
20K	/var/lib/mysql/httparchive/requestsmobiledev.frm
20K	/var/lib/mysql/httparchive/requestsiphone.frm
20K	/var/lib/mysql/httparchive/requestsie.frm
20K	/var/lib/mysql/httparchive/requests.frm
20K	/var/lib/mysql/httparchive/requestsdevSAVE.frm
20K	/var/lib/mysql/httparchive/requestsdev.frm
20K	/var/lib/mysql/httparchive/requestschrome.frm
20K	/var/lib/mysql/httparchive/requestsandroid.frm
4.0K	/var/lib/mysql/httparchive/requestschrome.MYI
0	/var/lib/mysql/httparchive/requestschrome.MYD
```

**Comment by rviscomi** [comment]
```sh
mysql> show tables;
+-----------------------+
| Tables_in_httparchive |
+-----------------------+
| cdf                   |
| crawls                |
| pages                 |
| pagesandroid          |
| pageschrome           |
| pagesdev              |
| pagesie               |
| pagesiphone           |
| pagesmobile           |
| pagesmobiledev        |
| requests              |
| requestsandroid       |
| requestschrome        |
| requestsdev           |
| requestsdevSAVE       |
| requestsie            |
| requestsiphone        |
| requestsmobile        |
| requestsmobiledev     |
| settings              |
| stats                 |
| statsdev              |
| status                |
| statusandroid         |
| statuschrome          |
| statusdev             |
| statusie              |
| statusiphone          |
| statusmobile          |
| urls                  |
| urlschange            |
| urlsdev               |
+-----------------------+
```

It might not make sense to run the cleanup script over deprecated tables since all of it can be removed. A more direct method could just be to drop the table.

Pat also suggests dropping `requests(chrome|mobile)` because only their `dev` versions are used by the UI.

```sql
USE httparchive;
DROP TABLE pagesandroid, pagesie, pagesiphone, \
requestsandroid, requestsie, requestsiphone, requestschrome, requestsmobile, \
statusandroid, statusie, statusiphone;
```

Bad idea? Anything off?

**Comment by igrigorik** [comment]
> DROP TABLE pagesandroid, pagesie..

👍

**Comment by rviscomi** [comment]
Dropped tables.

```
du -h /var/lib/mysql/httparchive/requests* | sort -hr
295G	/var/lib/mysql/httparchive/requests.MYD
240G	/var/lib/mysql/httparchive/requestsdev.MYD
57G	/var/lib/mysql/httparchive/requests.MYI
56G	/var/lib/mysql/httparchive/requestsdevSAVE.MYD
50G	/var/lib/mysql/httparchive/requestsdev.MYI
7.7G	/var/lib/mysql/httparchive/requestsdevSAVE.MYI
4.2G	/var/lib/mysql/httparchive/requestsmobiledev.MYD
861M	/var/lib/mysql/httparchive/requestsmobiledev.MYI
20K	/var/lib/mysql/httparchive/requestsmobiledev.frm
20K	/var/lib/mysql/httparchive/requests.frm
20K	/var/lib/mysql/httparchive/requestsdevSAVE.frm
20K	/var/lib/mysql/httparchive/requestsdev.frm
```

Overall utilization now at 42%. (was 95% during cleanup script!)

**Comment by pmeenan** [comment]
I wouldn't expect the desktop tables to be so much bigger than mobile (295GB vs 4.2G).  Did we either over-clean the mobile or not fully clean the desktop tables?  It looks like we usually grow around 160GB per crawl (total) so maybe a combination of the two?

Dropping the SAVE version of requestsdev also looks like it would recover ~60GB

**Comment by rviscomi** [comment]
Yeah something's not right.

> over-clean

What's the right way to verify this? Going through the historical data on the site, everything seems to be WAI.

> not fully clean

The cleanup script was aborted while optimizing the requestsmobile table because the disk utilization spiked up to 95% . So it never actually ran on desktop. I'll rerun the script after #100 and whenever there's some downtime in the crawl.

Speaking of requestsmobile, it was dropped per https://github.com/HTTPArchive/httparchive/issues/96#issuecomment-298093129 but it's back from the dead now that the 5/1 crawl has started (~1GB). I need to better understand how this is used.

I agree with your ~160GB/crawl approximation. Do we know how much of that is db vs other test artifacts?

**Comment by pmeenan** [comment]
Once the crawl completes the tables aren't used for anything.  They are only used while calculating the stats from the crawl itself.  Something at the end of the crawl runs some aggregations against the requests table and stores the aggregates for the UI to use.

The only reason they are kept around at all is more for an ability to re-run data from the last X crawls in case something went wrong (but it would have to have gone wrong in just the right way that we still had data for it).  I'd be perfectly happy just dropping all of the requests tables after each crawl :-)

As far as it's coming back from the dead, there may be code that automatically creates them if they are missing though that wouldn't explain the size unless the crawl ends up writing to both of them.

No test artifacts are kept on the server.  All of the crawl growth is in the database.  Some of it (the pages table) is unavoidable and will continue to grow but it should be marginal.  The vast majority of the persistent storage (90+% of it) is the requests tables.

**Comment by rviscomi** [comment]
Interesting to see how the disk usage per table is changing during the crawl:

```
295G	/var/lib/mysql/httparchive/requests.MYD
274G	/var/lib/mysql/httparchive/requestsdev.MYD
58G	/var/lib/mysql/httparchive/requestsdev.MYI
57G	/var/lib/mysql/httparchive/requests.MYI
56G	/var/lib/mysql/httparchive/requestsdevSAVE.MYD
31G	/var/lib/mysql/httparchive/requestsmobile.MYD
7.7G	/var/lib/mysql/httparchive/requestsdevSAVE.MYI
6.9G	/var/lib/mysql/httparchive/requestsmobile.MYI
4.2G	/var/lib/mysql/httparchive/requestsmobiledev.MYD
861M	/var/lib/mysql/httparchive/requestsmobiledev.MYI
20K	/var/lib/mysql/httparchive/requestsmobile.frm
20K	/var/lib/mysql/httparchive/requestsmobiledev.frm
20K	/var/lib/mysql/httparchive/requests.frm
20K	/var/lib/mysql/httparchive/requestsdevSAVE.frm
20K	/var/lib/mysql/httparchive/requestsdev.frm
```

It doesn't seem like requests is written to at all. Just requestsdev (+34GB) and requestsmobile (+7GB). Is it expected for mobile to grow so much more slowly? (fewer requests, smaller responses, etc?)

**Comment by pmeenan** [comment]
In general, I think all of the actual activity is in dev during a crawl and then copied to non-dev after the crawl completes.  We should be able to drop "requests" entirely and get rid of the copy step for the requests data since it isn't used in the UI.

**Comment by Themanwithoutaplan** [comment]
My MySQL foo isn't up to much but for such limited use the index looks oversized. On a related note pages contain a totally redundant hash column that could and should be replace by an appropriate index.

**Comment by rviscomi** [comment]
Did a complete run of the cleanup script before the current crawl. Behold:

![image](https://user-images.githubusercontent.com/1120896/26897970-55d52fec-4b98-11e7-8652-7f03cc1b367f.png)

^ the first big drop was from dropping tables on [4/28](https://github.com/HTTPArchive/httparchive/issues/96#issuecomment-298123417) and the second big drop was from cleaning up stale test data on ~5/29.
